version: '3.8'

services:
  temporal:
    image: temporalio/admin-tools:latest
    ports:
      - "7233:7233"
      - "8233:8233"
    entrypoint: []
    command: ["temporal", "server", "start-dev", "--ui-port", "8233", "--ip", "0.0.0.0"]
    networks:
      - temporal-net     # attach to the shared network

  worker:
    build: ./retryAndTimeoutHandlingWorkflow
    volumes:
      - ./retryAndTimeoutHandlingWorkflow:/app
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    # command: ["python", "-u", "worker.py"]
    networks:
      - temporal-net     # attach to the shared network

networks:
  temporal-net:          # declares the network so Docker Compose creates it
    driver: bridge       # default driver (could omit—bridge is the default)